config/routes.rb
Rails.application.routes.draw do

  # home page
  get "/" => "home#show", :as => 'home'
  get "/home" => "home#login", :as => "home-page"

  # generate user config info csv
  get "/generate-userdata" => "userconfig#show", :as => "user_config"
  post "/generate-userdata" => "userconfig#generate_csv", :as => "generate_csv"


  # dashboard
  get "/dashboard" => "dashboard#show", :as => 'dashboard'
  get "/dashboard/:id" => "dashboard#show", :as => 'dashboard_id'
  get "/delete/:id" => "dashboard#delete_file", :as => "delete_file"
  get "/download/:id" => 'dashboard#download', :as => "download"
  get "/share/:id" => "dashboard#share_file", :as => "share_file"
  get "/unshare/:id" => "dashboard#unshare_file", :as => "unshare_file"
  post "/upload/:folder_id" => "dashboard#upload", :as => "upload"
  post "/edit_name/:folder_id" => "dashboard#edit_filename", :as => "edit_name"
  post "/edit_folder_name/:folder_id" => "dashboard#edit_folder_name", :as => "edit_folder_name"
  post "/new_folder/:parent_id" => "dashboard#new_folder", :as => "new_folder"
  get "/delete_folder/:id" => "dashboard#delete_folder", :as => "delete_folder"
  get "/move_file" => "dashboard#move_file", :as => "move_file"
  get "/move_folder" => "dashboard#move_folder", :as => "move_folder"

  # view page
  get "/view_doc/:id" => "view#show", :as => "view_doc"
  get "/download_file/:id" => 'view#download', :as => "download_file"
  post "/comment/:id" => "view#comment", :as => "comment"
  get "/preview/:id" => 'view#preview', :as => "preview"
  get "/no_support" => 'view#no_support', :as => "no_support"

  get "/doc/:id" => "dashboard#doc", :as => 'doc'
  get "/thumbnail/:id" => 'dashboard#thumbnail', :as => "thumbnail"

  # search page
  post "/resources" => "search#show", :as => "search"
  get "/resources" => "search#show", :as => "resources"
  get "/resources/:folder_id" => "search#show", :as => "resources1"
  post "/resources/:folder_id" => "search#show", :as => "sub_resource"

  # workflow
  get "/onboarding-tasks" => "workflow#show", :as => "workflow"
  post "/onboarding-tasks" => "workflow#form_submit", :as => "form_submit"
  post "/onboarding-tasks-volunteer" => "workflow#volunteer_form_submit", :as => "volunteer_form_submit"
  get "docusign_response/:envelope_id" => "workflow#docusign_response", :as => "docusign_response"
  get "/onboarding-tasks/reset-workflow" => "workflow#reset_workflow", :as => "reset_workflow"

  # Upload and Sign
  get "/upload-sign" => "uploadsign#show", :as => "uploadsign"
  post "/upload-sign/:folder_id" => "uploadsign#sign_upload", :as => "sign_upload"
  get "/upload-sign-docusign/:id" => "uploadsign#start_docusign", :as => "start_docusign_id"
  get "uploadsign_docusign_response/:envelope_id" => "uploadsign#uploadnsign_docusign_response", :as => "uploadnsign_docusign_response"
  get "/reset-upload-sign" => "uploadsign#reset_uploadnsign", :as => "reset_uploadnsign"
  get "/delete_uploadnsign/:id" => "uploadsign#delete_file", :as => "delete_uploadnsign_file"

  # medical credentialing
  get "/medical-credentialing" => "medical_credentialing#show", :as => "medical"
  post "/medical-credentialing" => "medical_credentialing#medical_form_submit", :as => "medical_submit"
  get "/medical-credentialing-submit-upload" => "medical_credentialing#medical_upload", :as => "medical_upload"
  post "/medical-upload/:folder_id" => "medical_credentialing#med_upload", :as => "med_upload"
  get "/reset-medical" => "medical_credentialing#reset_workflow", :as => "reset_medical_flow"
  get "/medical-credentialist" => "medical_credentialing#credentialist", :as => "credentialist"
  get "/credentialist-approve/:folder_id" => "medical_credentialing#approve_request", :as => "approve_request"

  #loan documents
  get "/loan-origination" => "loan_documents#show", :as => "loan_docs"
  post "/loan-origination/:file_name" => "loan_documents#loan_post", :as => "loan_post"
  post "/loan-origination-dropzone/:file_name" => "loan_documents#loan_upload", :as => "loan_upload"
  get "/copy-from-vault/:file_id" => "loan_documents#copy_from_vault", :as => "copy_from_vault"
  get "/reset-loan-docs" => "loan_documents#reset_loan", :as => "reset_loan_docs"
  get "/loan-agreement-sign/:file_id" => "loan_documents#loan_docusign", :as => "loan_docusign"
  get "docusign_response_loan/:envelope_id" => "loan_documents#docusign_response_loan", :as => "docusign_response_loan"

  # account submission
  get "/account-submission" => "account_submission#show", :as => "acct_sub"
  post "/account-submission/create-acct" => "account_submission#create_acct", :as => "create_acct"
  get "/account-submission/list-acct/:id" => "account_submission#list_account", :as => "list_account"
  post "/account-submission/list-acct/:id" => "account_submission#upload_new_version", :as => "acct_sub_version"
  post "/account-submission/:folder_id" => "account_submission#account_doc_upload", :as => "account_doc_upload"
  # get "/copy-from-vault/:file_id" => "account_submission#copy_from_vault", :as => "copy_from_vault_acct"
  get "/reset-acct-docs" => "account_submission#reset_accts", :as => "reset_acct_docs"
  get "/prequal-submit/:folderId" => "account_submission#prequal_submit", :as => "prequal_submit"

  # create a claim
  get "/submit-claim" => "create_claim#show", :as => "create_claim"
  get "/claim-info/:file_id" => "create_claim#claim_info", :as => "claim_info"
  post "/submit-claim" => "create_claim#submit_claim", :as => "submit_claim"
  get "/reset-claims" => "create_claim#claim_reset", :as => "claim_reset"

  # dicom viewer
  get "/dicom_viewer" => "dicom_viewer#show", :as => "dicom_viewer"
  get "/dicom_view/:file_id" => "dicom_viewer#view", :as => "dicom_view"
  get "/dicom_upload" => 'dicom_viewer#upload', :as => 'dicom_upload'

  # auth0
  get "/auth0/failure" => "auth0#failure"
  get "/auth0/callback" => "auth0#callback"

  # okta
  get "/okta" => "okta#show", :as => "okta_login"
  get "/okta/callback" => "okta#callback"
  get "/okta/sign-up" => "okta#signup", :as => "okta_signup"
  post "/okta/sign-up-submit" => "okta#signup_submit", :as => "signup_submit"

  get '/logout' => 'home#logout', :as => "logout"
  get '/reset-logins' => 'home#reset_logins', :as => "reset_logins"

  # config page
  get '/config' => "config#show", :as => 'config'
  get '/config-reset' => "config#reset_config", :as => "reset_config"
  get '/config-industry' => "config#configure_industry", :as => "configure_industry"
  post '/config' => "config#post_config", :as => "save_config"

  # tax return
  get "/tax_return" => "tax_return#show", :as => "tax_return"
  get "/tax_create-claim" => "tax_return#show", :as => "tax_create_claim"
  post "/tax_submit-claim" => "tax_return#submit_claim", :as => "tax_submit_claim"
  get "/tax_reset-claims" => "tax_return#tax_reset", :as => "tax_reset"

  # upload route
  post "/tax-upload/:filename" => "tax_return#tax_upload", :as => "tax_upload"

  # tax return - search process
  get "/tax_copy-from-vault/:file_id" => "tax_return#tax_copy_from_vault", :as => "tax_copy_from_vault"
  get "/tax_loan-agreement-sign/:file_id" => "tax_return#tax_loan_docusign", :as => "tax_loan_docusign"
  get "tax_docusign_response_loan/:envelope_id" => "tax_return#tax_docusign_response_loan", :as => "tax_docusign_response_loan"

  get "/delete-tax-file/:id" => "tax_return#delete_file", :as => "delete_tax_file"
  get "/download/:id" => 'tax_return#download', :as => "download_tax_file"
  get "/income_file" => "tax_return#income_file_upload", :as => "income_file_upload"
  get "/forms_file" => "tax_return#forms_file_upload", :as => "forms_file_upload"
  get "/deductions_file" => "tax_return#deductions_file_upload", :as => "deduction_file_upload"
  get "/metadata_upload" => "tax_return#metadata_upload", :as => "tax_metadata_upload"
  post "/advisor_task" => "tax_return#advisor_task", :as => "advisor_task"

  # media content
  get "/media-content" => "media_content#show", :as => "media_content"
  post "/media-content/search" => "media_content#search_show", :as => "search_show"

  # box events
  get "/event-activity" => "eventstream#show", :as => "eventstream"

  # user management
  get "/user-management" => "user_management#show", :as => "user_management"
  post "/user-management/provision-okta-user" => "user_management#provision_okta_user", :as => "provision_okta"
  post "/user-management/delete-user" => "user_management#delete_user", :as => "delete_user"
  get "/user-management-password" => "user_management#enter_password", :as => "enter_password"
  post "/user-management-password" => "user_management#enter_password_submit", :as => "enter_password_submit"

  #request for proposal
  get "/request_for_proposal" => "request_for_proposal#show", :as => "request_for_proposal"
  post "/req_create_folder" => "request_for_proposal#create_folder", :as => "rfp_create_folder"
  post "req_upload" => "request_for_proposal#upload_file", :as => "rfp_upload_file"
  get "/rfp_reset" => "request_for_proposal#reset", :as => "rfp_reset"
  get 'shared_link' => "request_for_proposal#enable_shared_link", :as => "rfp_enable_shared_link"
  get 'disable_shared_link' => "request_for_proposal#disable_shared_link", :as => "rfp_disable_shared_link"
  post "/rfp_send_grid_message" => "request_for_proposal#send_grid_method", :as => "rfp_send_grid"

  # product supply
  get "/product-supply" => "product_supply#show", :as => "product_supply"
  post "/update-cart" => "product_supply#update_cart"
  post "/order-supplies" => "product_supply#order_supplies"
  get "/order-sign/:file_id" => "product_supply#order_docusign", :as => "order_docusign"
  get "docusign_response_order/:envelope_id" => "product_supply#docusign_response_order", :as => "docusign_response_order"
  get "/reset-orders" => "product_supply#product_supply_reset", :as => "product_supply_reset"


  #third-party api's
  post "/send_twilio_message" => "config#twilio_method"
  post "/send_grid_message" => "config#send_grid_method", :as => "send_grid_method"

  #metadata form

app/views/tax_return/_tax_modals.html.haml
-# All modals on this page

-# Modals for local upload
#loanModal.modal
  .modal-content
    %h5{:style => "margin-bottom: 35px;"} Upload Your Loan Agreement
    .drop-area
      .row
        .col-md-12
          = simple_form_for(:vault, html:{class: 'dropzone', id:'my-dropzone'}, url: tax_loan_upload_url("Loan Agreement - Signature Needed"))  {}
  .modal-footer
    %a.modal-action.modal-close.btn-flat{:href => "#!", :style => "text-decoration: none;"} Close

#w2Modal.modal
  .modal-content
    %h5{:style => "margin-bottom: 35px;"} Upload Your W2 Form
    .drop-area
      .row
        .col-md-12
          = simple_form_for(:vault, html:{class: 'dropzone', id:'my-dropzone'}, url: tax_loan_upload_url("W2 Form"))  {}
  .modal-footer
    %a.modal-action.modal-close.btn-flat{:href => "#!", :style => "text-decoration: none;"} Close

#taxModal.modal
  .modal-content
    %h5{:style => "margin-bottom: 35px;"} Upload Your Tax Return
    .drop-area
      .row
        .col-md-12
          = simple_form_for(:vault, html:{class: 'dropzone', id:'my-dropzone'}, url: tax_loan_upload_url("Tax Return"))  {}
  .modal-footer
    %a.modal-action.modal-close.btn-flat{:href => "#!", :style => "text-decoration: none;"} Close

-# Modals for upload suggestions
#loanVaultDocs.modal
  .modal-content
    %h5{:style => "margin-bottom: 35px;"} Loan Agreement Suggestions
    .collection.with-header
      .collection-header
        Suggested items from your vault
      - if !@searchFiles["Loan"].nil?
        - @searchFiles["Loan"].each do |f|
          %a.collection-item{:href => tax_copy_from_vault_path(f.id, new_name: "Loan Agreement - Signature Needed", old_name: f.name), :style => "text-decoration: none;"}
            = f.name
  .modal-footer
    %a.modal-action.modal-close.btn-flat.modal-trigger{:href => "#loanModal", :style => "text-decoration: none;"}
      Upload New Loan Agreement

#w2VaultDocs.modal
  .modal-content
    %h5{:style => "margin-bottom: 35px;"} W2 Form Suggestions
    .collection.with-header
      .collection-header
        Suggested items from your vault
      - if !@searchFiles["W2"].nil?
        - @searchFiles["W2"].each do |f|
          %a.collection-item{:href => tax_copy_from_vault_path(f.id, new_name: "W2 Form", old_name: f.name), :style => "text-decoration: none;"}
            = f.name
  .modal-footer
    %a.modal-action.modal-close.btn-flat.modal-trigger{:href => "#w2Modal", :style => "text-decoration: none;"}
      Upload New W2 Form

#taxVaultDocs.modal
  .modal-content
    %h5{:style => "margin-bottom: 35px;"} Tax Return Suggestions
    .collection.with-header
      .collection-header
        Suggested items from your vault
      - if !@searchFiles["Tax"].nil?
        - @searchFiles["Tax"].each do |f|
          %a.collection-item{:href => tax_copy_from_vault_path(f.id, new_name: "Tax Return", old_name: f.name), :style => "text-decoration: none;"}
            = f.name
  .modal-footer
    %a.modal-action.modal-close.btn-flat.modal-trigger{:href => "#taxModal", :style => "text-decoration: none;"}
      Upload New Tax Return

app/views/tax_return/deductions_file_upload.html.haml
.container
  = render 'layouts/sidenav'
  .row
    .index-banner.section.no-pad-bot
  .row
    .col.s10.push-s2
      .col.s2.push-s10{:style => "margin-top: 80px;"}
        %h7.hide_below768
          Step 1 of 2
    .col.s10.push-s2
      .drop-area
        .row
          .col-md-12{:style => "margin-top: 35px;"}
            = simple_form_for(:vault, html:{class: 'dropzone', id:'my-dropzone'}, url: tax_upload_url("Deductions (Not Signed)"))  {}
      %a.button.waves-effect.btn.white.black-text.modal-trigger{:href => "tax_return", :style => "text-decoration: none; font-size: 10px;"} Back
      %a.button.waves-effect.btn.white.black-text.modal-trigger{:href => "metadata_upload", :style => "text-decoration: none; font-size: 10px;"} Next

app/views/tax_return/forms_file_upload.html.haml
.container
  = render 'layouts/sidenav'
  .row
    .index-banner.section.no-pad-bot
  .row
    .col.s10.push-s2
      .col.s2.push-s10{:style => "margin-top: 80px;"}
        %h7.hide_below768
          Step 1 of 2
    .col.s10.push-s2
      .drop-area
        .row
          .col-md-12{:style => "margin-top: 35px;"}
            = simple_form_for(:vault, html:{class: 'dropzone', id:'my-dropzone'}, url: tax_upload_url("Forms (Not Signed)"))  {}
      %a.button.waves-effect.btn.white.black-text.modal-trigger{:href => "tax_return", :style => "text-decoration: none; font-size: 10px;"} Back
      %a.button.waves-effect.btn.white.black-text.modal-trigger{:href => "metadata_upload", :style => "text-decoration: none; font-size: 10px;"} Next

app/views/tax_return/income_file_upload.html.haml
.container
  = render 'layouts/sidenav'
  .row
    .index-banner.section.no-pad-bot
  .row
    .col.s10.push-s2
      .col.s2.push-s10{:style => "margin-top: 80px;"}
        %h7.hide_below768
          Step 1 of 2
    .col.s10.push-s2
      .drop-area
        .row
          .col-md-12{:style => "margin-top: 35px;"}
            = simple_form_for(:vault, html:{class: 'dropzone', id:'my-dropzone'}, url: tax_upload_url("Income (Not Signed)"))  {}
      %a.button.waves-effect.btn.white.black-text.modal-trigger{:href => "tax_return", :style => "text-decoration: none; font-size: 10px;"} Back
      %a.button.waves-effect.btn.white.black-text.modal-trigger{:href => "metadata_upload", :style => "text-decoration: none; font-size: 10px;"} Next

app/views/tax_return/metadata_upload.html.haml
.container
  = render 'layouts/sidenav'
  .row
    .index-banner.section.no-pad-bot
  .row
    .col.s10.push-s2
      .col.s2.push-s10{:style => "margin-top: 80px;"}
        %h7.hide_below768
          Step 2 of 2
      .col.s12{:style => "margin-top: 30px"}
        .col.s5
          %h6
            Categorize Your Tax Document
      .col.s8.push-s2{:style => "margin-top: 20px"}
        %form{:role => "form", :method => "post", :action => tax_submit_claim_path, :style => "height: 900px;"}
          %label{:for => "category"}
            %select#type{:placeholder => "Category", :type => "text", :name => "category"}
              %option{:disabled => "", :selected => "", :value => ""} Choose your option
              %option{:value => "Taxes"} Taxes
              %option{:value => "Income"} Income
              %option{:value => "Credits"} Credits
          .form-group
            #Taxes.style-sub-1{:name => "stylesub1", :onchange => "ChangeDropdowns(this.value)", :style => "display: none;"}
              %label{:for => "subcategory"}
                %select#type{:placeholder => "subCategory", :type => "text", :name => "subcategory"}
                  %option{:disabled => "", :selected => "", :value => ""} Choose your option
                  %option Not specified
                  %option Form 1040-ES
                  %option Schedule H
            #Income.style-sub-1{:name => "stylesub1", :onchange => "ChangeDropdowns(this.value)", :style => "display: none;"}
              %label{:for => "subcategory"}
                %select#type{:placeholder => "subCategory", :type => "text", :name => "subcategory"}
                  %option{:disabled => "", :selected => "", :value => ""} Choose your option
                  %option Form W-2
                  %option Form 1099-G
                  %option Form 1099-INT
                  %option Form 1099-DIV (Dividend Income)
                  %option Form 1099-R (Retirement Income)
                  %option Form SSA-1099 (Social Security Income)
                  %option Schedule C
            #Credits.style-sub-1{:name => "stylesub1", :onchange => "ChangeDropdowns(this.value)", :style => "display: none;"}
              %label{:for => "subcategory"}
                %select#type{:placeholder => "subCategory", :type => "text", :name => "subcategory"}
                  %option{:disabled => "", :selected => "", :value => ""}
                  %option Not Specified
                  %option Child and Dependent Care Expenses
                  %option Form 1098-T (Tuition and Expenses)
                  %option Mortgage Interest Credit
          %input{:name => "formSubmit", :type => "hidden", :value => "true"}
          .form-group
            -# %a.waves-effect.btn.white.black-text{:type => "submit", :href => "#modal1", :style => "font-color: #263238 !important; text-decoration: none;"} Submit for Approval
            %button.waves-effect.btn.white.black-text{:type => "submit", :style => "text-decoration: none;"} Submit
:javascript
  $(document).ready(function() {
    $('select').material_select();
  });
  $("#type").change ( function () {
      var targID  = $(this).val ();
      $("div.style-sub-1").hide ();
      $('#' + targID).show ();
  })

app/views/tax_return/tax_loan_docusign.html.haml
.row
  %h5(style="font-size: 120%;")
    = link_to '<< Back to my taxes', '/tax_return'
  .container(style="text-align:center;")
    %iframe{:src => @url, :width => '960px', :height => '850px', :frameBorder => '0', :allowfullscreen => 'allowfullscreen'}