config/routes.rb
Rails.application.routes.draw do

  # home page
  get "/" => "home#show", :as => 'home'
  get "/home" => "home#login", :as => "home-page"

  # generate user config info csv
  get "/generate-userdata" => "userconfig#show", :as => "user_config"
  post "/generate-userdata" => "userconfig#generate_csv", :as => "generate_csv"


  # dashboard
  get "/dashboard" => "dashboard#show", :as => 'dashboard'
  get "/dashboard/:id" => "dashboard#show", :as => 'dashboard_id'
  get "/delete/:id" => "dashboard#delete_file", :as => "delete_file"
  get "/download/:id" => 'dashboard#download', :as => "download"
  get "/share/:id" => "dashboard#share_file", :as => "share_file"
  get "/unshare/:id" => "dashboard#unshare_file", :as => "unshare_file"
  post "/upload/:folder_id" => "dashboard#upload", :as => "upload"
  post "/edit_name/:folder_id" => "dashboard#edit_filename", :as => "edit_name"
  post "/edit_folder_name/:folder_id" => "dashboard#edit_folder_name", :as => "edit_folder_name"
  post "/new_folder/:parent_id" => "dashboard#new_folder", :as => "new_folder"
  get "/delete_folder/:id" => "dashboard#delete_folder", :as => "delete_folder"
  get "/move_file" => "dashboard#move_file", :as => "move_file"
  get "/move_folder" => "dashboard#move_folder", :as => "move_folder"

  # view page
  get "/view_doc/:id" => "view#show", :as => "view_doc"
  get "/download_file/:id" => 'view#download', :as => "download_file"
  post "/comment/:id" => "view#comment", :as => "comment"
  get "/preview/:id" => 'view#preview', :as => "preview"
  get "/no_support" => 'view#no_support', :as => "no_support"

  get "/doc/:id" => "dashboard#doc", :as => 'doc'
  get "/thumbnail/:id" => 'dashboard#thumbnail', :as => "thumbnail"

  # search page
  post "/resources" => "search#show", :as => "search"
  get "/resources" => "search#show", :as => "resources"
  get "/resources/:folder_id" => "search#show", :as => "resources1"
  post "/resources/:folder_id" => "search#show", :as => "sub_resource"

  # workflow
  get "/onboarding-tasks" => "workflow#show", :as => "workflow"
  post "/onboarding-tasks" => "workflow#form_submit", :as => "form_submit"
  post "/onboarding-tasks-volunteer" => "workflow#volunteer_form_submit", :as => "volunteer_form_submit"
  get "docusign_response/:envelope_id" => "workflow#docusign_response", :as => "docusign_response"
  get "/onboarding-tasks/reset-workflow" => "workflow#reset_workflow", :as => "reset_workflow"

  # Upload and Sign
  get "/upload-sign" => "uploadsign#show", :as => "uploadsign"
  post "/upload-sign/:folder_id" => "uploadsign#sign_upload", :as => "sign_upload"
  get "/upload-sign-docusign/:id" => "uploadsign#start_docusign", :as => "start_docusign_id"
  get "uploadsign_docusign_response/:envelope_id" => "uploadsign#uploadnsign_docusign_response", :as => "uploadnsign_docusign_response"
  get "/reset-upload-sign" => "uploadsign#reset_uploadnsign", :as => "reset_uploadnsign"
  get "/delete_uploadnsign/:id" => "uploadsign#delete_file", :as => "delete_uploadnsign_file"

  # medical credentialing
  get "/medical-credentialing" => "medical_credentialing#show", :as => "medical"
  post "/medical-credentialing" => "medical_credentialing#medical_form_submit", :as => "medical_submit"
  get "/medical-credentialing-submit-upload" => "medical_credentialing#medical_upload", :as => "medical_upload"
  post "/medical-upload/:folder_id" => "medical_credentialing#med_upload", :as => "med_upload"
  get "/reset-medical" => "medical_credentialing#reset_workflow", :as => "reset_medical_flow"
  get "/medical-credentialist" => "medical_credentialing#credentialist", :as => "credentialist"
  get "/credentialist-approve/:folder_id" => "medical_credentialing#approve_request", :as => "approve_request"

  #loan documents
  get "/loan-origination" => "loan_documents#show", :as => "loan_docs"
  post "/loan-origination/:file_name" => "loan_documents#loan_post", :as => "loan_post"
  post "/loan-origination-dropzone/:file_name" => "loan_documents#loan_upload", :as => "loan_upload"
  get "/copy-from-vault/:file_id" => "loan_documents#copy_from_vault", :as => "copy_from_vault"
  get "/reset-loan-docs" => "loan_documents#reset_loan", :as => "reset_loan_docs"
  get "/loan-agreement-sign/:file_id" => "loan_documents#loan_docusign", :as => "loan_docusign"
  get "docusign_response_loan/:envelope_id" => "loan_documents#docusign_response_loan", :as => "docusign_response_loan"

  # account submission
  get "/account-submission" => "account_submission#show", :as => "acct_sub"
  post "/account-submission/create-acct" => "account_submission#create_acct", :as => "create_acct"
  get "/account-submission/list-acct/:id" => "account_submission#list_account", :as => "list_account"
  post "/account-submission/list-acct/:id" => "account_submission#upload_new_version", :as => "acct_sub_version"
  post "/account-submission/:folder_id" => "account_submission#account_doc_upload", :as => "account_doc_upload"
  # get "/copy-from-vault/:file_id" => "account_submission#copy_from_vault", :as => "copy_from_vault_acct"
  get "/reset-acct-docs" => "account_submission#reset_accts", :as => "reset_acct_docs"
  get "/prequal-submit/:folderId" => "account_submission#prequal_submit", :as => "prequal_submit"

  # create a claim
  get "/submit-claim" => "create_claim#show", :as => "create_claim"
  get "/claim-info/:file_id" => "create_claim#claim_info", :as => "claim_info"
  post "/submit-claim" => "create_claim#submit_claim", :as => "submit_claim"
  get "/reset-claims" => "create_claim#claim_reset", :as => "claim_reset"

  # dicom viewer
  get "/dicom_viewer" => "dicom_viewer#show", :as => "dicom_viewer"
  get "/dicom_view/:file_id" => "dicom_viewer#view", :as => "dicom_view"
  get "/dicom_upload" => 'dicom_viewer#upload', :as => 'dicom_upload'

  # auth0
  get "/auth0/failure" => "auth0#failure"
  get "/auth0/callback" => "auth0#callback"

  # okta
  get "/okta" => "okta#show", :as => "okta_login"
  get "/okta/callback" => "okta#callback"
  get "/okta/sign-up" => "okta#signup", :as => "okta_signup"
  post "/okta/sign-up-submit" => "okta#signup_submit", :as => "signup_submit"

  get '/logout' => 'home#logout', :as => "logout"
  get '/reset-logins' => 'home#reset_logins', :as => "reset_logins"

  # config page
  get '/config' => "config#show", :as => 'config'
  get '/config-reset' => "config#reset_config", :as => "reset_config"
  get '/config-industry' => "config#configure_industry", :as => "configure_industry"
  post '/config' => "config#post_config", :as => "save_config"

  # tax return
  get "/tax_return" => "tax_return#show", :as => "tax_return"
  get "/tax_create-claim" => "tax_return#show", :as => "tax_create_claim"
  post "/tax_submit-claim" => "tax_return#submit_claim", :as => "tax_submit_claim"
  get "/tax_reset-claims" => "tax_return#tax_reset", :as => "tax_reset"

  # upload route
  post "/tax-upload/:filename" => "tax_return#tax_upload", :as => "tax_upload"

  # tax return - search process
  get "/tax_copy-from-vault/:file_id" => "tax_return#tax_copy_from_vault", :as => "tax_copy_from_vault"
  get "/tax_loan-agreement-sign/:file_id" => "tax_return#tax_loan_docusign", :as => "tax_loan_docusign"
  get "tax_docusign_response_loan/:envelope_id" => "tax_return#tax_docusign_response_loan", :as => "tax_docusign_response_loan"

  get "/delete-tax-file/:id" => "tax_return#delete_file", :as => "delete_tax_file"
  get "/download/:id" => 'tax_return#download', :as => "download_tax_file"
  get "/income_file" => "tax_return#income_file_upload", :as => "income_file_upload"
  get "/forms_file" => "tax_return#forms_file_upload", :as => "forms_file_upload"
  get "/deductions_file" => "tax_return#deductions_file_upload", :as => "deduction_file_upload"
  get "/metadata_upload" => "tax_return#metadata_upload", :as => "tax_metadata_upload"
  post "/advisor_task" => "tax_return#advisor_task", :as => "advisor_task"

  # media content
  get "/media-content" => "media_content#show", :as => "media_content"
  post "/media-content/search" => "media_content#search_show", :as => "search_show"

  # box events
  get "/event-activity" => "eventstream#show", :as => "eventstream"

  # user management
  get "/user-management" => "user_management#show", :as => "user_management"
  post "/user-management/provision-okta-user" => "user_management#provision_okta_user", :as => "provision_okta"
  post "/user-management/delete-user" => "user_management#delete_user", :as => "delete_user"
  get "/user-management-password" => "user_management#enter_password", :as => "enter_password"
  post "/user-management-password" => "user_management#enter_password_submit", :as => "enter_password_submit"

  #request for proposal
  get "/request_for_proposal" => "request_for_proposal#show", :as => "request_for_proposal"
  post "/req_create_folder" => "request_for_proposal#create_folder", :as => "rfp_create_folder"
  post "req_upload" => "request_for_proposal#upload_file", :as => "rfp_upload_file"
  get "/rfp_reset" => "request_for_proposal#reset", :as => "rfp_reset"
  get 'shared_link' => "request_for_proposal#enable_shared_link", :as => "rfp_enable_shared_link"
  get 'disable_shared_link' => "request_for_proposal#disable_shared_link", :as => "rfp_disable_shared_link"
  post "/rfp_send_grid_message" => "request_for_proposal#send_grid_method", :as => "rfp_send_grid"

  # product supply
  get "/product-supply" => "product_supply#show", :as => "product_supply"
  post "/update-cart" => "product_supply#update_cart"
  post "/order-supplies" => "product_supply#order_supplies"
  get "/order-sign/:file_id" => "product_supply#order_docusign", :as => "order_docusign"
  get "docusign_response_order/:envelope_id" => "product_supply#docusign_response_order", :as => "docusign_response_order"
  get "/reset-orders" => "product_supply#product_supply_reset", :as => "product_supply_reset"


  #third-party api's
  post "/send_twilio_message" => "config#twilio_method"
  post "/send_grid_message" => "config#send_grid_method", :as => "send_grid_method"

  #metadata form

app/controllers/search_controller.rb
class SearchController < SecuredController

  skip_before_filter :verify_authenticity_token
  BOX_CLIENT = HTTPClient.new
  # BOX_CLIENT.cookie_manager = nil
  BOX_CLIENT.send_timeout = 3600 #one hour; needed for lengthy uploads

  # main search page controller
  def show

    # get user client to make API calls
    client = user_client
    @results = nil
    @industry = false
    session[:current_page] = "search"
    mixpanel_tab_event("Resources", "Main Page")
    
    # has this been configured for an industry?
    if (!session[:industry_resources].nil?)
      @industry = true
      resourceFolderId = session[:industry_resources]

      # get root industry resource folder
      resource = Rails.cache.fetch("/resource_folder/#{resourceFolderId}", :expires_in => 15.minutes) do
        puts "miss"
        client.folder_from_id(resourceFolderId, fields: [:id, :name, :size])
      end
      # need roots, subname, and results
      if(params[:folder_id].nil?)
        @root = true
        @results = Rails.cache.fetch("/resource_folder/#{resourceFolderId}/subfolders", :expires_in => 15.minutes) do
          client.folder_items(resourceFolderId, fields: [:id, :name, :content_modified_at, :description])
        end
      else
        # get subfolder contents and subfolder name
        @results = Rails.cache.fetch("/resource_folder/#{resourceFolderId}/#{params[:folder_id]}", :expires_in => 15.minutes) do
          puts "miss"
          client.folder_items(params[:folder_id], fields: [:id, :name, :created_at, :parent])
        end

        # get subfolder
        subFolder = @results.first.parent
        @subName = subFolder.name
      end

    # get generic resource folder
    else

      # get root resource folder
      @resource = Rails.cache.fetch("/resource_folder/#{ENV['RESOURCE_FOLDER']}", :expires_in => 15.minutes) do
        puts "miss"
        client.folder_from_id(ENV['RESOURCE_FOLDER'], fields: [:id, :name, :size])
      end

      # check if search query was entered
      if((params[:search].nil? or params[:search][:query] == "") and params[:filter_query].nil?)
        # search query was not entered

        # Check if we are in the root resource folder or a sub-resource folder
        if(params[:folder_id].nil?)
          # in root resource folder

          # get resource subfolder objects
          @results = Rails.cache.fetch("/resource_folder/#{ENV['RESOURCE_FOLDER']}/subfolders", :expires_in => 15.minutes) do
            client.folder_items(ENV['RESOURCE_FOLDER'], fields: [:id, :name, :content_modified_at, :description])
          end

          # tell view that we are in the root resource folder
          @root = true
        else
          # in a resource subfolder

          # get subfolder contents and subfolder name
          @results = Rails.cache.fetch("/resource_folder/#{ENV['RESOURCE_FOLDER']}/#{params[:folder_id]}", :expires_in => 15.minutes) do
            puts "miss"
            client.folder_items(params[:folder_id], fields: [:id, :name, :created_at, :parent])
          end

          # get subfolder
          subFolder = @results.first.parent
          @subName = subFolder.name
          session[:current]
        end
      else
        # a search query was enterd

        # search based on search text query or filter query
        if(!params[:search].nil?)
          @text = params[:search][:query]
        else
          @text = params[:filter_query]
        end

        # perform Box search, get results
        if (!params[:search].nil?)
          @results = client.search(@text, content_types: :name, ancestor_folder_ids: ENV['RESOURCE_FOLDER'])
          @search_type = "file name"
          mixpanel_tab_event("Resources", "Search File Name")
        elsif (params[:filter] == "file_type")
          @results = client.search(@text, content_types: :name, file_extensions: @text, ancestor_folder_ids: ENV['RESOURCE_FOLDER'])
          @search_type = "file type"
          mixpanel_tab_event("Resources", "Search File Type")
        else
          mixpanel_tab_event("Resources", "Search Metadata")
          mdfilters = {"templateKey" => "#{ENV['METADATA_KEY']}", "scope" => "enterprise",
                       "filters" => {"#{params["key"]}" => "#{params["filter_query"]}"}}
          @results = client.search(mdfilters: mdfilters, ancestor_folder_ids: ENV['RESOURCE_FOLDER'])
          # @search_type = params["key"]

          # little hack to change message name
          if(params["key"] == 'type')
            @search_type = "category"
          elsif(params["key"] == 'audience')
            @search_type = "privacy"
          end
        end

        @results = @results.files
      end

      # set current folder session variable
      if (!@subName.nil?)
        session[:rfolder] = subFolder.id
      else
        session[:rfolder] = ""
      end


      # attach metadata to each result file if we're not in the root folder
      if (@root.nil?)
        @results.each do |r|
          class << r
            attr_accessor :type, :audience
          end

          begin
            meta = Rails.cache.fetch("/metadata/#{r.id}", :expires_in => 15.minutes) do
              puts "miss"
              client.all_metadata(r)["entries"]
            end

            meta.each do |m|
              if (m["$template"] == "#{ENV['METADATA_KEY']}")
                r.type = m["type"]
                r.audience = m["audience"]
              end
            end

          rescue
            r.type = ""
            r.audience = ""
          end
        end
      end
    end

  end

  def processed_response(res)
    body_json = Oj.load(res.body)
    return BoxrMash.new(body_json)
  end

end

app/views/search/_industry.html.haml
// Messaging
.col.s5.push-s7{:style => "margin-top:-20px; text-align: right"}
  .styleoverlay{:style => "margin-left: 130px;"}
  - if @root == true
    .breadcrumb.hide_mobile
      %li
        %li.active{:href => "#", "data-intro" => "Your current folder path. On creation of your App User you were granted Viewer access to these folders", "data-position" => "bottom"} Resources
  - elsif !@subName.nil?
    .breadcrumb.hide_mobile{:style => "vertical-align: top"}
      %li{ "data-intro" => "Look here for a breadcrumb view of your current folder", "data-position" => "bottom"}
        %a{:href => "/resources"} Resources
      %li.active{:href => "#", :style => ""}
        = @subName

// Results: folders or files
.col.s12{:style => "margin-left: 30px"}
  - if (@root == true)
    %table.highlight.resources_table
      %thead
        %tr
          %th{"data-field" => "id"} Folder
          %th{"data-field" => "name"} Name
          %th{"data-field" => "modified"} Last Modified
          %th{"data-field" => "modified"} Description
      - @results.each_with_index do |folder, i|
        %tr{:onclick => "location.href = '/resources/#{folder.id}'"}
          %td{"data-intro" => i==0 ? "We've added your App User to the 'Customer' group in Box with access to these folders. Search or click to navigate content." : nil,  "data-position" => i==0 ? "left" : nil}
            = image_tag("https://hostr.co/file/eMmzO9cqCEjm/Folder.png", height: '50px')
          %td
            .filename.name_elipses{:style => "font-size: 16px; color: #333 !important; text-decoration: none;"}
              = link_to folder.name, sub_resource_path(folder.id), {:style=>'color:#333; text-decoration: none; font-size: 14px;'}
          %td
            .name_elipses
              = DateTime.strptime(folder.content_modified_at).strftime("%B %d, %Y")
          %td
            .name_elipses
              = folder.description
  - if (@root != true)
    %table.highlight.resources_table
      %thead
        %tr
          %th{"data-field" => "id"} File
          %th{"data-field" => "name"} Name
          %th.hide_mobile{"data-field" => "foop"} Created


      - @results.each_with_index do |result, i|
        %tr{"data-lity" => "", :href => preview_url(result.id), :class => "tooltipped", 'data-position'=>"left", 'data-delay'=>"50", 'data-tooltip'=>"View"}
          %td{"data-intro" => i==0 ? "Each of these documents are viewable in the browser via the Box Preview endpoint" : nil,  "data-position" => i==0 ? "left" : nil}
            = image_tag(thumbnail_url(result.id), :width => "40px")
          %td
            .name_elipses
              = result.name
          %td.hide_mobile
            .name_elipses
              = DateTime.strptime(result.created_at).strftime("%B %d, %Y %l:%M %p")

app/views/search/show.html.haml
.container
  = render 'layouts/sidenav'
  .row
    .index-banner.section.no-pad-bot
  .row
    .col.m12.l10.push-l2{:style => "margin-top: 25px;"}
      // title
      .col.s12
        %h3.thin{:style => "margin-top: 40px; font-size: 28px; letter-spacing: 1.5px; text-color: #002557;"}
          %span.glyphicon.glyphicon-sort-by-attributes-alt{:style => "font-size: 22px;"}
          = alt_text("Resources")
        %h6.caption.thin{:style => "font-size: 16px;"}
          = alt_text("Find relevant content, fast")
        .help-icon.btn.hide_mobile{"data-toggle" => "chardinjs", :id => "opentour", :onclick => "chardinToggle()", :style => "padding: none; font-color: #fff !important;"}
          %i.material-icons.prefix{:style => "font-size: 18px; color: #222222;"} info_outline
          %span{:style => "color: #222222; position: relative; top: -4px; left: 0px; text-transform: lowercase; font-size: 12px;"}
            info

      - if !@industry
        // Messaging
        .col.s5.push-s7{:style => "margin-top:-20px; text-align: right"}
          .styleoverlay{:style => "margin-left: 130px;"}
          - if (!@text.nil?)
            = "Found #{@results.count} results for #{@search_type}: '#{@text}'"
          - elsif @root == true
            .breadcrumb.hide_mobile
              %li
                %li.active{:href => "#", "data-intro" => "Your current folder path. On creation of your App User you were granted Viewer access to these folders", "data-position" => "bottom"} Resources
          - elsif !@subName.nil?
            .breadcrumb.hide_mobile{:style => "vertical-align: top"}
              %li{ "data-intro" => "Look here for a breadcrumb view of your current folder", "data-position" => "bottom"}
                %a{:href => "/resources"} Resources
              %li.active{:href => "#", :style => ""}
                = @subName


        // Search and filtering\
        .col.s12#search{:style => "margin-top: 50px; margin-left: 60px;"}
          = simple_form_for(:search, html: {class: 'form-search'}, :url => "#", defaults: { label: false }) do |f|
            // input
            .col.s3
              = f.input :query, placeholder: "Search...", input_html: {:style => "size: 40; height: 1.05rem;", :type => "text", class: 'search', id: 'search', "data-intro" => "Leverage Box's search api capabilities to query against file name, type, metadata, and more", "data-position" => "bottom"}
            // search button
            -# .col.s2
            -#   = f.button :submit, "Submit", :style => "margin-top: 5px;", class: 'btn white black-text'
            // file type filter
            .filters{:style => "margin-left: 300px;"}
              .filtergroup_m{:style => "margin-left: 0px;"}
                .col.s4.filter_m{:style => "z-index: 9999999 !important; width: 100px;", "data-intro" => "Filter search results by file type and metadata templates. Each of these dropdowns represent metadata values in Box", "data-position" => "bottom"}
                  %span.border-select
                    %a.dropdown-button{"data-activates" => "dropdown1", :href => "#!", :style => "color: black;"}
                      %i.material-icons arrow_drop_down
                      Type
                  %ul.dropdown-content{:id => "dropdown1",}
                    %li
                      = link_to "pdf", search_path(:filter_query => "pdf", :filter => "file_type"), :method => :post, :style => "text-decoration: none"
                    %li
                      = link_to 'docx', search_path(:filter_query => "docx", :filter => "file_type"), :method => :post, :style => "text-decoration: none"
                    %li
                      = link_to 'pptx', search_path(:filter_query => "pptx", :filter => "file_type"), :method => :post, :style => "text-decoration: none"
                    %li
                      = link_to 'xlsx', search_path(:filter_query => "xlsx", :filter => "file_type"), :method => :post, :style => "text-decoration: none"
                // category filter
                .col.s4.filter_m{:style => "width: 120px;"}
                  %span.border-select
                    %a.dropdown-button{"data-activates" => "dropdown2", :href => "#!", :style => "color: black"}
                      %i.material-icons arrow_drop_down
                      Category
                  %ul.dropdown-content{:id => "dropdown2"}
                    %div{:style => "text-overflow: ellipsis; width: 7em; overflow: hidden; white-space: nowrap; list-style-position:inside;"}
                      %li
                        = link_to "Training", search_path(:filter_query => "Training Material", :key => "type"), :method => :post, :style => "text-decoration: none"
                    %li
                      = link_to 'Onboard', search_path(:filter_query => "Onboarding Document", :key => "type"), :method => :post, :style => "text-decoration: none"
                    %li
                      = link_to 'Research', search_path(:filter_query => "Case Study", :key => "type"), :method => :post, :style => "text-decoration: none"
                // privacy filter
                .col.s4.filter_m{:style => "100px;"}
                  %span.border-select
                    %a.dropdown-button{"data-activates" => "dropdown3", :href => "#!", :style => "color: black"}
                      %i.material-icons arrow_drop_down
                      Privacy
                  %ul.dropdown-content{:id => "dropdown3"}
                    %li
                      = link_to "External", search_path(:filter_query => "External", :key => "audience"), :method => :post, :style => "text-decoration: none"
                    %li
                      = link_to 'Internal', search_path(:filter_query => "Internal", :key => "audience"), :method => :post, :style => "text-decoration: none"

        // Results: folders, search, filter
        .col.s12{:style => "margin-left: 30px"}
          - if @results.nil? or @results.count == 0
            %h6.center{:style => "margin-top: 35px;"}
              There were no results matching your search criteria.
          - else
            / either results were found for your search or were are in the resource root folder / sub-folder
            / are we in the root folder?
            - if (@root == true)
              -# .nav-wrapper
              -#   %a.breadcrumb{:href => "/resources"}
              -#     Resources
              -#   %a.breadcrumb{:href => "#!"}
              %table.highlight.resources_table
                %thead
                  %tr
                    %th{"data-field" => "id"} Folder
                    %th{"data-field" => "name"} Name
                    %th{"data-field" => "modified"} Last Modified
                    %th{"data-field" => "modified"} Description
                - @results.each_with_index do |folder, i|
                  %tr{:onclick => "location.href = '/resources/#{folder.id}'"}
                    %td{"data-intro" => i==0 ? "We've added your App User to the 'Customer' group in Box with access to these folders. Search or click to navigate content." : nil,  "data-position" => i==0 ? "left" : nil}
                      = image_tag("https://hostr.co/file/eMmzO9cqCEjm/Folder.png", height: '50px')
                    %td
                      .filename.name_elipses{:style => "font-size: 16px; color: #333 !important; text-decoration: none;"}
                        = link_to folder.name, sub_resource_path(folder.id), {:style=>'color:#333; text-decoration: none; font-size: 14px;'}
                    %td
                      .name_elipses
                        = DateTime.strptime(folder.content_modified_at).strftime("%B %d, %Y")
                    %td
                      .name_elipses
                        = folder.description
            - if (@root != true)
              %table.highlight.resources_table
                %thead
                  %tr
                    %th{"data-field" => "id"} File
                    %th{"data-field" => "name"} Name
                    %th{"data-field" => "price"} Category
                    %th.hide_mobile{"data-field" => "foop"} Created
                    %th{"data-field" => "foop"} Privacy


                - @results.each_with_index do |result, i|
                  %tr{"data-lity" => "", :href => preview_url(result.id), :class => "tooltipped", 'data-position'=>"left", 'data-delay'=>"50", 'data-tooltip'=>"View"}
                    %td{"data-intro" => i==0 ? "Each of these documents are viewable in the browser via the Box Preview endpoint" : nil,  "data-position" => i==0 ? "left" : nil}
                      = image_tag(thumbnail_url(result.id), :width => "40px")
                    %td
                      .name_elipses
                        = result.name
                    %td
                      .name_elipses
                        = result.type
                    %td.hide_mobile
                      .name_elipses
                        = DateTime.strptime(result.created_at).strftime("%B %d, %Y %l:%M %p")
                    %td
                      .name_elipses
                        = result.audience
      - else
        = render 'search/industry'


#viewModal.modal.modal-fixed-footer{:style => "height: 80%; max-height: 80%; background-color: white"}
  .modal-content
    %iframe{:id => 'preview', :width => '100%', :height => '100%', :frameborder => '0', :allowfullscreen => "", :width => '100%', :height => '100%'}
  .modal-footer
    %a.modal-action.modal-close.waves-effect.waves-green.btn-flat{:href => "#!", :style => "text-decoration: none;"} Close

:javascript

  $(document).ready(function() {
    $('select').material_select();
  });

  $(document).ready(function(){
    $('.collapsible').collapsible({
      accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
  });

  function chardinToggle() {
    $('body').chardinJs('toggle');
  }