config/routes.rb
Rails.application.routes.draw do

  # home page
  get "/" => "home#show", :as => 'home'
  get "/home" => "home#login", :as => "home-page"

  # generate user config info csv
  get "/generate-userdata" => "userconfig#show", :as => "user_config"
  post "/generate-userdata" => "userconfig#generate_csv", :as => "generate_csv"


  # dashboard
  get "/dashboard" => "dashboard#show", :as => 'dashboard'
  get "/dashboard/:id" => "dashboard#show", :as => 'dashboard_id'
  get "/delete/:id" => "dashboard#delete_file", :as => "delete_file"
  get "/download/:id" => 'dashboard#download', :as => "download"
  get "/share/:id" => "dashboard#share_file", :as => "share_file"
  get "/unshare/:id" => "dashboard#unshare_file", :as => "unshare_file"
  post "/upload/:folder_id" => "dashboard#upload", :as => "upload"
  post "/edit_name/:folder_id" => "dashboard#edit_filename", :as => "edit_name"
  post "/edit_folder_name/:folder_id" => "dashboard#edit_folder_name", :as => "edit_folder_name"
  post "/new_folder/:parent_id" => "dashboard#new_folder", :as => "new_folder"
  get "/delete_folder/:id" => "dashboard#delete_folder", :as => "delete_folder"
  get "/move_file" => "dashboard#move_file", :as => "move_file"
  get "/move_folder" => "dashboard#move_folder", :as => "move_folder"

  # view page
  get "/view_doc/:id" => "view#show", :as => "view_doc"
  get "/download_file/:id" => 'view#download', :as => "download_file"
  post "/comment/:id" => "view#comment", :as => "comment"
  get "/preview/:id" => 'view#preview', :as => "preview"
  get "/no_support" => 'view#no_support', :as => "no_support"

  get "/doc/:id" => "dashboard#doc", :as => 'doc'
  get "/thumbnail/:id" => 'dashboard#thumbnail', :as => "thumbnail"

  # search page
  post "/resources" => "search#show", :as => "search"
  get "/resources" => "search#show", :as => "resources"
  get "/resources/:folder_id" => "search#show", :as => "resources1"
  post "/resources/:folder_id" => "search#show", :as => "sub_resource"

  # workflow
  get "/onboarding-tasks" => "workflow#show", :as => "workflow"
  post "/onboarding-tasks" => "workflow#form_submit", :as => "form_submit"
  post "/onboarding-tasks-volunteer" => "workflow#volunteer_form_submit", :as => "volunteer_form_submit"
  get "docusign_response/:envelope_id" => "workflow#docusign_response", :as => "docusign_response"
  get "/onboarding-tasks/reset-workflow" => "workflow#reset_workflow", :as => "reset_workflow"

  # Upload and Sign
  get "/upload-sign" => "uploadsign#show", :as => "uploadsign"
  post "/upload-sign/:folder_id" => "uploadsign#sign_upload", :as => "sign_upload"
  get "/upload-sign-docusign/:id" => "uploadsign#start_docusign", :as => "start_docusign_id"
  get "uploadsign_docusign_response/:envelope_id" => "uploadsign#uploadnsign_docusign_response", :as => "uploadnsign_docusign_response"
  get "/reset-upload-sign" => "uploadsign#reset_uploadnsign", :as => "reset_uploadnsign"
  get "/delete_uploadnsign/:id" => "uploadsign#delete_file", :as => "delete_uploadnsign_file"

  # medical credentialing
  get "/medical-credentialing" => "medical_credentialing#show", :as => "medical"
  post "/medical-credentialing" => "medical_credentialing#medical_form_submit", :as => "medical_submit"
  get "/medical-credentialing-submit-upload" => "medical_credentialing#medical_upload", :as => "medical_upload"
  post "/medical-upload/:folder_id" => "medical_credentialing#med_upload", :as => "med_upload"
  get "/reset-medical" => "medical_credentialing#reset_workflow", :as => "reset_medical_flow"
  get "/medical-credentialist" => "medical_credentialing#credentialist", :as => "credentialist"
  get "/credentialist-approve/:folder_id" => "medical_credentialing#approve_request", :as => "approve_request"

  #loan documents
  get "/loan-origination" => "loan_documents#show", :as => "loan_docs"
  post "/loan-origination/:file_name" => "loan_documents#loan_post", :as => "loan_post"
  post "/loan-origination-dropzone/:file_name" => "loan_documents#loan_upload", :as => "loan_upload"
  get "/copy-from-vault/:file_id" => "loan_documents#copy_from_vault", :as => "copy_from_vault"
  get "/reset-loan-docs" => "loan_documents#reset_loan", :as => "reset_loan_docs"
  get "/loan-agreement-sign/:file_id" => "loan_documents#loan_docusign", :as => "loan_docusign"
  get "docusign_response_loan/:envelope_id" => "loan_documents#docusign_response_loan", :as => "docusign_response_loan"

  # account submission
  get "/account-submission" => "account_submission#show", :as => "acct_sub"
  post "/account-submission/create-acct" => "account_submission#create_acct", :as => "create_acct"
  get "/account-submission/list-acct/:id" => "account_submission#list_account", :as => "list_account"
  post "/account-submission/list-acct/:id" => "account_submission#upload_new_version", :as => "acct_sub_version"
  post "/account-submission/:folder_id" => "account_submission#account_doc_upload", :as => "account_doc_upload"
  # get "/copy-from-vault/:file_id" => "account_submission#copy_from_vault", :as => "copy_from_vault_acct"
  get "/reset-acct-docs" => "account_submission#reset_accts", :as => "reset_acct_docs"
  get "/prequal-submit/:folderId" => "account_submission#prequal_submit", :as => "prequal_submit"

  # create a claim
  get "/submit-claim" => "create_claim#show", :as => "create_claim"
  get "/claim-info/:file_id" => "create_claim#claim_info", :as => "claim_info"
  post "/submit-claim" => "create_claim#submit_claim", :as => "submit_claim"
  get "/reset-claims" => "create_claim#claim_reset", :as => "claim_reset"

  # dicom viewer
  get "/dicom_viewer" => "dicom_viewer#show", :as => "dicom_viewer"
  get "/dicom_view/:file_id" => "dicom_viewer#view", :as => "dicom_view"
  get "/dicom_upload" => 'dicom_viewer#upload', :as => 'dicom_upload'

  # auth0
  get "/auth0/failure" => "auth0#failure"
  get "/auth0/callback" => "auth0#callback"

  # okta
  get "/okta" => "okta#show", :as => "okta_login"
  get "/okta/callback" => "okta#callback"
  get "/okta/sign-up" => "okta#signup", :as => "okta_signup"
  post "/okta/sign-up-submit" => "okta#signup_submit", :as => "signup_submit"

  get '/logout' => 'home#logout', :as => "logout"
  get '/reset-logins' => 'home#reset_logins', :as => "reset_logins"

  # config page
  get '/config' => "config#show", :as => 'config'
  get '/config-reset' => "config#reset_config", :as => "reset_config"
  get '/config-industry' => "config#configure_industry", :as => "configure_industry"
  post '/config' => "config#post_config", :as => "save_config"

  # tax return
  get "/tax_return" => "tax_return#show", :as => "tax_return"
  get "/tax_create-claim" => "tax_return#show", :as => "tax_create_claim"
  post "/tax_submit-claim" => "tax_return#submit_claim", :as => "tax_submit_claim"
  get "/tax_reset-claims" => "tax_return#tax_reset", :as => "tax_reset"

  # upload route
  post "/tax-upload/:filename" => "tax_return#tax_upload", :as => "tax_upload"

  # tax return - search process
  get "/tax_copy-from-vault/:file_id" => "tax_return#tax_copy_from_vault", :as => "tax_copy_from_vault"
  get "/tax_loan-agreement-sign/:file_id" => "tax_return#tax_loan_docusign", :as => "tax_loan_docusign"
  get "tax_docusign_response_loan/:envelope_id" => "tax_return#tax_docusign_response_loan", :as => "tax_docusign_response_loan"

  get "/delete-tax-file/:id" => "tax_return#delete_file", :as => "delete_tax_file"
  get "/download/:id" => 'tax_return#download', :as => "download_tax_file"
  get "/income_file" => "tax_return#income_file_upload", :as => "income_file_upload"
  get "/forms_file" => "tax_return#forms_file_upload", :as => "forms_file_upload"
  get "/deductions_file" => "tax_return#deductions_file_upload", :as => "deduction_file_upload"
  get "/metadata_upload" => "tax_return#metadata_upload", :as => "tax_metadata_upload"
  post "/advisor_task" => "tax_return#advisor_task", :as => "advisor_task"

  # media content
  get "/media-content" => "media_content#show", :as => "media_content"
  post "/media-content/search" => "media_content#search_show", :as => "search_show"

  # box events
  get "/event-activity" => "eventstream#show", :as => "eventstream"

  # user management
  get "/user-management" => "user_management#show", :as => "user_management"
  post "/user-management/provision-okta-user" => "user_management#provision_okta_user", :as => "provision_okta"
  post "/user-management/delete-user" => "user_management#delete_user", :as => "delete_user"
  get "/user-management-password" => "user_management#enter_password", :as => "enter_password"
  post "/user-management-password" => "user_management#enter_password_submit", :as => "enter_password_submit"

  #request for proposal
  get "/request_for_proposal" => "request_for_proposal#show", :as => "request_for_proposal"
  post "/req_create_folder" => "request_for_proposal#create_folder", :as => "rfp_create_folder"
  post "req_upload" => "request_for_proposal#upload_file", :as => "rfp_upload_file"
  get "/rfp_reset" => "request_for_proposal#reset", :as => "rfp_reset"
  get 'shared_link' => "request_for_proposal#enable_shared_link", :as => "rfp_enable_shared_link"
  get 'disable_shared_link' => "request_for_proposal#disable_shared_link", :as => "rfp_disable_shared_link"
  post "/rfp_send_grid_message" => "request_for_proposal#send_grid_method", :as => "rfp_send_grid"

  # product supply
  get "/product-supply" => "product_supply#show", :as => "product_supply"
  post "/update-cart" => "product_supply#update_cart"
  post "/order-supplies" => "product_supply#order_supplies"
  get "/order-sign/:file_id" => "product_supply#order_docusign", :as => "order_docusign"
  get "docusign_response_order/:envelope_id" => "product_supply#docusign_response_order", :as => "docusign_response_order"
  get "/reset-orders" => "product_supply#product_supply_reset", :as => "product_supply_reset"


  #third-party api's
  post "/send_twilio_message" => "config#twilio_method"
  post "/send_grid_message" => "config#send_grid_method", :as => "send_grid_method"

  #metadata form

app/views/medical_credentialing/_medical_approved.html.haml
.col.s2.push-s10{:style => "margin-top:-20px;"}
  %h7.hide_below768{:style => "z-index: 999999;", "data-intro" => "Your current progress in this workflow", "data-position" => "left"}
    Complete!
.col.s8.push-s2{:style => "margin-top: 30px;"}
  .flash
    = render partial: "shared/flash_messages", flash: flash
.col.s5
  %h6{:style => "margin-bottom: 20px"}
    Approved medical credential documents:
.col.s10.push-s1
  .panel.panel-default{:style => "margin-bottom: 0px"}
    %table.highlight
      %thead
        %tr
          %th File
          %th Name
          %th.hidden-xs.hidden-sm Date Modified
          %th Actions
        %tbody
          / list file contents
          - @medFiles.each do |f|
            %tr
              %td
                = link_to view_doc_path(f.id) do
                  = image_tag(thumbnail_url(f.id), width: '40px')
              %td
                %span{:style => "inline"}
                  = f.name
              %td.hidden-xs.hidden-sm
                = DateTime.strptime(f.modified_at).strftime("%B %d, %Y %l:%M %p")
              %td
                / file action options
                .btn-group
                  %a.btn.white.tooltipped{href: view_doc_path(f.id), 'data-position'=>"top", 'data-delay'=>"50", 'data-tooltip'=>"View", :style => "padding-right: 9px; padding-left: 9px;"}
                    %span.glyphicon.glyphicon-eye-open{:style => "top: 3px; color: #263238"}
                  %a.btn.white.tooltipped{href: download_path(f.id), 'data-position'=>"top", 'data-delay'=>"50", 'data-tooltip'=>"Download", :style => "padding-right: 9px; padding-left: 9px;"}
                    %span.glyphicon.glyphicon-download{:style => "top: 3px; color: #263238"}

app/views/medical_credentialing/_medical_form.html.haml
.col.s2.push-s10{:style => "margin-top:-20px;"}
  %h7.hide_below768{:style => "z-index: 999999;", "data-intro" => "Your current progress in this workflow", "data-position" => "left"}
    Step 1 of 3
.col.s12{:style => "margin-top: 30px"}
  %h6
    Enter your personal information here:
.col.s8.push-s2{:style => "margin-top: 20px", "data-intro" => "A pdf is generated from this form information and uploaded to the newly created 'Medical Credentialing' folder. The Credentialing Specialist is invited into this folder and a task to review uploaded documents is assigned.", "data-position" => "left"}
  %form.form-horizontal{:role => "form", :method => "post", :action => medical_submit_path, :style => "height: 700px;"}
    .form-group
      %label.control-label.col-sm-2{:for => "name"} Full Name:
      %input#name.form-control{:placeholder => "Marcus Doe", :type => "text", :name => "name"}
    .form-group
      %label.control-label.col-sm-2{:for => "date"} Date of Birth:
      %input#date.form-control{:type => "date", :name => "date"}
    .form-group
      %label.control-label.col-sm-2{:for => "id"} Medical License Number:
      %input#id.form-control{:type => "text", :placeholder => "123456789", :name => "id"}
    .form-group
      %label.control-label.col-sm-3{:for => "degree"} Specialty:
      .col-sm-6
        %select#specialty.form-control{:placeholder => "Specialty", :type => "text", :name => "specialty"}
          %option{:disabled => "", :selected => "", :value => ""} Choose your option
          %option Anesthesiology
          %option Cardiology
          %option Neurology
          %option Nurse Practitioner
          %option Radiology
          %option Registed Nurse
    .form-group
      %label.control-label.col-sm-3{:for => "degree"} Degree Type:
      .col-sm-6
        %select#degree.form-control{:placeholder => "Degree", :type => "text", :name => "degree"}
          %option{:disabled => "", :selected => "", :value => ""} Choose your option
          %option MD
          %option DO
    %input{:name => "formSubmit", :type => "hidden", :value => "true"}
    .form-group
      %button.waves-effect.btn.white.black-text{:type => "submit", :style => "text-decoration: none;"} Submit

:javascript

  $(document).ready(function() {
    $('select').material_select();
  });

app/views/medical_credentialing/_medical_pending.html.haml
.col.s2.push-s10{:style => "margin-top:-20px;"}
  %h7.hide_below768{:style => "z-index: 999999;", "data-intro" => "Your current progress in this workflow", "data-position" => "left"}
    Step 3 of 3
.col.s8.push-s2{:style => "margin-top: 30px;"}
  .flash
    = render partial: "shared/flash_messages", flash: flash
.col.s5
  %h6{:style => "margin-bottom: 40px"}
    Wait for credentialing specialist to review & approve:
.col.s10.push-s1
  .panel.panel-default{:style => "margin-bottom: 0px"}
    .panel-heading
      %h6{:style => "height: 130%"}
        Shared Medical Credential Documents
    %table.highlight.medcred_table
      %thead
        %tr
          %th File
          %th Name
          %th.hidden-xs.hidden-sm Date Modified
          %th Actions
        %tbody
          / list file contents
          - @medFiles.each_with_index do |f, i|
            %tr
              %td
                = link_to view_doc_path(f.id) do
                  = image_tag(thumbnail_url(f.id), width: '40px')
              %td
                %div.name_elipses{:style => "inline"}
                  = f.name
              %td.hidden-xs.hidden-sm
                %div.name_elipses{:style => "inline"}
                  = DateTime.strptime(f.modified_at).strftime("%B %d, %Y %l:%M %p")
              %td{"data-intro" => i==0 ? "View and download files files from Box" : nil,  "data-position" => i==0 ? "left" : nil}
                / file action options
                .btn-group
                  %a.btn.white.tooltipped{href: view_doc_path(f.id), 'data-position'=>"top", 'data-delay'=>"50", 'data-tooltip'=>"View", :style => "padding-right: 9px; padding-left: 9px;"}
                    %span.glyphicon.glyphicon-eye-open{:style => "top: 3px; color: #263238"}
                  %a.btn.white.tooltipped{href: download_path(f.id), 'data-position'=>"top", 'data-delay'=>"50", 'data-tooltip'=>"Download", :style => "padding-right: 9px; padding-left: 9px;"}
                    %span.glyphicon.glyphicon-download{:style => "top: 3px; color: #263238"}

app/views/medical_credentialing/_upload_medical.html.haml
.col.s2.push-s10{:style => "margin-top:-20px;"}
  %h7.hide_below768{:style => "z-index: 999999;", "data-intro" => "Your current progress in this workflow", "data-position" => "left"}
    Step 2 of 3
.col.s8.push-s2{:style => "margin-top: 30px;"}
  .flash
    = render partial: "shared/flash_messages", flash: flash
.col.s5
  %h6{:style => "margin-bottom: 30px"}
    Upload supporting medical credential documents:
.col.s10.push-s1
  .drop-area
    = simple_form_for(:medical, html:{class: 'dropzone', id:'my-dropzone', :style => "height: 220px; margin-bottom: 40px"}, url: med_upload_url(@medFolder.id))  {}
    %form.form-horizontal{:role => "form", :method => "get", :action => medical_upload_path}
      .form-group
        .col.s5
          %button.waves-effect.btn.white.black-text{:type => "submit"} Submit

app/views/medical_credentialing/credentialist.html.haml
.container
  = render 'layouts/sidenav'
  .row
    .index-banner.section.no-pad-bot
  .row
    .col.m12.l10.push-l2{:style => "margin-top: 25px;"}
      // Title
      %h3.thin{:style => "margin-top: 40px; font-size: 28px; letter-spacing: 1.5px; text-color: #002557;"}
        %span.glyphicon.glyphicon-plus{:style => "font-size: 22px;"}
        Credentialing Specialist Requests
      %h6.caption.thin{:style => "font-size: 16px;"}
        Review and approve the submission(s) below
      // Message
      .col.s8.push-s2{:style => "margin-top: 30px;"}
        .flash
          = render partial: "shared/flash_messages", flash: flash
      // Table
      .col.s10.push-s1{:style => "padding: 0px; min-height: 470px"}
        / list file contents
        - if @empty == true
          %h6{:style => "text-align: center"}
            There are no open requests at this time
        - @medicalArray.each do |name, items|
          - if items.size >= 1
            .panel.panel-default{:style => "margin-bottom: 60px;"}
              .panel-heading
                .pull-right.h4
                  %form{:method => "get", :action => approve_request_path(items.first.parent.id)}
                    %button.waves-effect.btn.white.black-text{:type => "submit"}
                      Approve
                %h5 New Request
                %h7
                  = "#{name.split(" ").first}"
                -# .sub-title
                -#   = "Medical documents vault shared with medical credentialist"
              %table.highlight.cred_table
                %thead
                  %tr
                    %th File
                    %th Name
                    %th.hidden-xs.hidden-sm Date Modified
                    %th Actions
                  %tbody
                    - items.each do |f|
                      %tr.name
                        %td
                          = link_to view_doc_path(f.id) do
                            = image_tag(thumbnail_url(f.id), width: '40px')
                        %td
                          %div.name_elipses{:style => "inline"}
                            = f.name
                        %td.hidden-xs.hidden-sm
                          %div.name_elipses{:style => "inline"}
                            = DateTime.strptime(f.modified_at).strftime("%B %d, %Y %l:%M %p")
                        %td
                          / file action options
                          .btn-group
                            %a.btn.white.tooltipped{href: view_doc_path(f.id), 'data-position'=>"top", 'data-delay'=>"50", 'data-tooltip'=>"View", :style => "padding-right: 9px; padding-left: 9px;"}
                              %span.glyphicon.glyphicon-eye-open{:style => "top: 3px; color: #263238"}
                            %a.btn.white.tooltipped{href: download_path(f.id), 'data-position'=>"top", 'data-delay'=>"50", 'data-tooltip'=>"Download", :style => "padding-right: 9px; padding-left: 9px;"}
                              %span.glyphicon.glyphicon-download{:style => "top: 3px; color: #263238"}

app/views/medical_credentialing/show.html.haml
.container
  = render 'layouts/sidenav'
  .row
    .index-banner.section.no-pad-bot
  .row
    .col.m12.l10.push-l2{:style => "margin-top: 25px;"}
      %h3.thin{:style => "margin-top: 40px; font-size: 28px; letter-spacing: 1.5px; text-color: #002557;"}
        %span.glyphicon.glyphicon-plus{:style => "font-size: 22px;"}
        = alt_text("Medical Credentialing")
      %h6.caption.thin{:style => "font-size: 16px;"}
        = "Please complete the #{alt_text("Medical Credentialing").downcase} process"
      .help-icon.btn.hide_mobile{"data-toggle" => "chardinjs", :id => "opentour", :onclick => "chardinToggle()", :style => "padding: none; font-color: #fff !important;"}
        %i.material-icons.prefix{:style => "font-size: 18px; color: #222222;"} info_outline
        %span{:style => "color: #222222; position: relative; top: -4px; left: 0px; text-transform: lowercase; font-size: 12px;"}
          info

      - if (@status == "toFill")
        = render 'medical_form'
      - elsif (@status == "toUpload")
        = render 'upload_medical'
      - elsif (@status == "pendingApproval")
        = render 'medical_pending'
      - elsif (session[:progress] == 3)
        = render 'medical_approved'

.footer{:style=>"text-align: right; font-size: 10px;"}
  .right{:style => "margin-bottom: 25px;"}
    = link_to "reset", reset_medical_flow_path, {:style => "text-decoration: none;", "data-intro" => "Reset the Medical Credentialing workflow", "data-position" => "top"}


:javascript
  Dropzone.options.myDropzone = {
    init: function() {
      this.on("queuecomplete", function(file) {
        // setTimeout(function() {location.reload();}, 2000);
      });
    }
  };

:javascript
  function chardinToggle() {
    $('body').chardinJs('toggle');
  }